---
name: Addon Deploy

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      slug:
        description: Overrides the detected slug
        required: false
        type: string
      hassio-addons:
        default: "hassio-addons"
        description: The name of the stable repository
        required: false
        type: string
      hassio-addons-edge:
        default: "hassio-addons-edge"
        description: The name of the edge repository
        required: false
        type: string
    secrets:
      CAS_API_KEY:
        required: false
      DISPATCH_TOKEN:
        required: true

jobs:
  workflows:
    uses: hassio-addons/workflows/.github/workflows/addon-deploy.yaml@main
    secrets:
      CAS_API_KEY: ${{ secrets.CAS_API_KEY }}
      DISPATCH_TOKEN: ${{ secrets.DISPATCH_TOKEN }}
