---
name: PR Labels

# yamllint disable-line rule:truthy
on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize
  workflow_call:

jobs:
  workflows:
    uses: hassio-addons/workflows/.github/workflows/pr-labels.yaml@main
