---
name: Repository Updater

# yamllint disable-line rule:truthy
on:
  workflow_call:
    secrets:
      UPDATER_TOKEN:
        required: true

concurrency:
  group: queue

jobs:
  workflows:
    uses: hassio-addons/workflows/.github/workflows/repository-updater.yaml@main
